# Generated by Django 4.2.6 on 2023-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=50, null=True)),
                ('CourseID', models.CharField(max_length=50, null=True)),
                ('CourseCode', models.CharField(max_length=50, null=True)),
                ('YearAndSection', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.DecimalField(decimal_places=1, max_digits=3)),
                ('DateReleased', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('MiddleName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50, null=True)),
                ('StudentID', models.IntegerField(blank=True)),
                ('YearAndSection', models.CharField(max_length=50, null=True)),
                ('Status', models.CharField(max_length=50, null=True)),
                ('Birthday', models.IntegerField(blank=True)),
                ('ContactNumber', models.IntegerField(blank=True)),
                ('Email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teachername', models.CharField(max_length=50, null=True)),
                ('Department', models.CharField(max_length=50, null=True)),
                ('Birthday', models.IntegerField(blank=True)),
                ('ContactNumber', models.IntegerField(blank=True)),
                ('Email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(default='images/default.png', upload_to='images/')),
            ],
        ),
    ]
