# Generated by Django 4.2.6 on 2023-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Birthday',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
