# Generated by Django 4.2.6 on 2023-12-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0003_alter_teacher_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.student'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='onlinegradetracker.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.student'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.teacher'),
        ),
    ]
