# Generated by Django 4.2.6 on 2024-01-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0005_rename_courses_studentprofile_courses_enrolled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='picture',
            new_name='Picture',
        ),
    ]
