# Generated by Django 4.2.6 on 2024-01-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0006_rename_picture_studentprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Status',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.student'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinegradetracker.teacher'),
        ),
    ]
