# Generated by Django 4.2.6 on 2024-01-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0007_alter_grade_course_alter_grade_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses_enrolled',
        ),
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(related_name='courses_enrolled', to='onlinegradetracker.student'),
        ),
    ]
