# Generated by Django 4.2.6 on 2024-01-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0008_remove_student_courses_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses_taught', to='onlinegradetracker.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course_taught',
            field=models.ManyToManyField(related_name='teachers_set', to='onlinegradetracker.course'),
        ),
    ]
