# Generated by Django 4.2.6 on 2024-01-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0009_course_teachers_alter_teacher_course_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
    ]
