# Generated by Django 4.2.6 on 2024-01-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0010_remove_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course_taught',
            field=models.ManyToManyField(related_name='teachers_courses', to='onlinegradetracker.course'),
        ),
    ]
