# Generated by Django 4.2.6 on 2024-01-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0012_grade_teacher_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseCode',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
