# Generated by Django 4.2.6 on 2024-01-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0013_alter_course_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students_enrolled',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', to='onlinegradetracker.student'),
        ),
    ]
