# Generated by Django 4.2.6 on 2024-01-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0014_alter_course_students_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='courses_enrolled',
        ),
    ]
