# Generated by Django 4.2.6 on 2024-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinegradetracker', '0016_alter_teacherprofile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='Picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
